# rubocop config files for small Rails4/Ruby2 project
# blog post: http://joanswork.com/rubocop-rails-getting-started/

# .rubocop.yml
AllCops:
  RunRailsCops: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb

LineLength:
  Max: 120 # revisit

SpaceInsideHashLiteralBraces:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false
