development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: n_if_l_development
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_pass %>


test:
  <<: *default
  database: n_if_l_test
