development: &default
  adapter: mysql2
  database: n_if_l_development
  username: root
  password:
  socket:  <%=
        ['/opt/local/var/run/mysql5/mysqld.sock', # darwinports
         '/opt/local/var/run/mysqld/mysqld.sock', # darwinports, again
         '/var/run/mysqld/mysqld.sock',           # ubuntu/debian
         '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>

test:
  <<: *default
  database: n_if_l_test
