development: &default
  adapter: postgresql
  database: n_if_l_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  user: daybreaker

test:
  <<: *default
  database: n_if_l_test
