default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  gmail_user: sdsdsdsd
  gmail_pass: sdsdsd
  facebook_key: 101880363481528
  facebook_secret: 5b6b11e5e0628baeb8ad4af300b4092e

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
