require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PicksetsController do

  # This should return the minimal set of attributes required to create a valid
  # Pickset. As you add validations to Pickset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PicksetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all picksets as @picksets" do
      pickset = Pickset.create! valid_attributes
      get :index, {}, valid_session
      assigns(:picksets).should eq([pickset])
    end
  end

  describe "GET show" do
    it "assigns the requested pickset as @pickset" do
      pickset = Pickset.create! valid_attributes
      get :show, {:id => pickset.to_param}, valid_session
      assigns(:pickset).should eq(pickset)
    end
  end

  describe "GET new" do
    it "assigns a new pickset as @pickset" do
      get :new, {}, valid_session
      assigns(:pickset).should be_a_new(Pickset)
    end
  end

  describe "GET edit" do
    it "assigns the requested pickset as @pickset" do
      pickset = Pickset.create! valid_attributes
      get :edit, {:id => pickset.to_param}, valid_session
      assigns(:pickset).should eq(pickset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pickset" do
        expect {
          post :create, {:pickset => valid_attributes}, valid_session
        }.to change(Pickset, :count).by(1)
      end

      it "assigns a newly created pickset as @pickset" do
        post :create, {:pickset => valid_attributes}, valid_session
        assigns(:pickset).should be_a(Pickset)
        assigns(:pickset).should be_persisted
      end

      it "redirects to the created pickset" do
        post :create, {:pickset => valid_attributes}, valid_session
        response.should redirect_to(Pickset.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pickset as @pickset" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pickset.any_instance.stub(:save).and_return(false)
        post :create, {:pickset => {  }}, valid_session
        assigns(:pickset).should be_a_new(Pickset)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pickset.any_instance.stub(:save).and_return(false)
        post :create, {:pickset => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pickset" do
        pickset = Pickset.create! valid_attributes
        # Assuming there are no other picksets in the database, this
        # specifies that the Pickset created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pickset.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => pickset.to_param, :pickset => { "these" => "params" }}, valid_session
      end

      it "assigns the requested pickset as @pickset" do
        pickset = Pickset.create! valid_attributes
        put :update, {:id => pickset.to_param, :pickset => valid_attributes}, valid_session
        assigns(:pickset).should eq(pickset)
      end

      it "redirects to the pickset" do
        pickset = Pickset.create! valid_attributes
        put :update, {:id => pickset.to_param, :pickset => valid_attributes}, valid_session
        response.should redirect_to(pickset)
      end
    end

    describe "with invalid params" do
      it "assigns the pickset as @pickset" do
        pickset = Pickset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pickset.any_instance.stub(:save).and_return(false)
        put :update, {:id => pickset.to_param, :pickset => {  }}, valid_session
        assigns(:pickset).should eq(pickset)
      end

      it "re-renders the 'edit' template" do
        pickset = Pickset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pickset.any_instance.stub(:save).and_return(false)
        put :update, {:id => pickset.to_param, :pickset => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pickset" do
      pickset = Pickset.create! valid_attributes
      expect {
        delete :destroy, {:id => pickset.to_param}, valid_session
      }.to change(Pickset, :count).by(-1)
    end

    it "redirects to the picksets list" do
      pickset = Pickset.create! valid_attributes
      delete :destroy, {:id => pickset.to_param}, valid_session
      response.should redirect_to(picksets_url)
    end
  end

end
